### PR TITLE
Replace method added for replacing all data with new

### PR DESCRIPTION
**Pull request by SinanMtl**

### CODE REVIEW

**Comment by SinanMtl** [comment]
Hey @eldomagan, Can you review and (if possible) merge and make release this, please? I need this improvement. Thank you :)

**Review by eldomagan — CHANGES_REQUESTED** [review]
@SinanMtl thanks for your contribution.

We don't really need to create a  separate action class. You can use the persist class as it is doing the same thing.

You can do something like this

```js
static replace(context, payload) {
    return this.call(context, payload, 'create');
}
```

And  in the call method
```js
if (action === 'create') {
   DestroyAll.clearDB(state);
}
```

**Comment by SinanMtl** [comment]
@eldomagan First, I was make what you recommended. But then, I think, it could be better with separated. If it is not problem to you, I can apply your recommend.

**Comment by eldomagan** [comment]
We should keep it in Persist class to avoid duplicated code and make updates easier.

**Comment by eldomagan** [comment]
@SinanMtl I just published a new release. Thank for your contribution.

**Pull request merged**
